blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/sawala-tech/sawala-tech-2022/discussions
    about: Ask questions and discuss with other community members
